apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: datasaur
  namespace: datasaur
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "301"
spec:
  rules:
  - host: datasaur.geeksops.com
    http:
      paths:
      - backend:
          serviceName: datasaur
          servicePort: 80
