apiVersion: v1
kind: Service
metadata:
  name: datasaur
  namespace: datasaur
  labels:
    app: datasaur
    env: staging
    type: service
spec:
  type: ClusterIP
  selector:
    app: datasaur
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
